### ISSUE TITLE
Vcaching causes 500 server errors

### ISSUE THREAD

**Issue by ahmed-sigmalux** [razvanstanga/varnish-caching-wordpress-plugin#4]
Out of nowhere, I started getting 500 server errors on my WordPress setup. The only way to restore my site was to disable the vcaching plugin. I tried uninstalling and reinstalling without success - if the plugin is enabled, my site won't load.

I think something is corrupted with the vcaching database or installation files because trying to access it via wp cli results in errors like:

PHP Fatal error:  Uncaught Error: Call to undefined method VCaching::purgeUrl() in /var/www/mysit/wp-content/plugins/vcaching/wp-cli.php:28
Stack trace:
#0 [internal function]: WP_CLI_VCaching_Purge_Command->purge(Array, Array)
#1 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(81): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(401): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(323): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(330): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(985): WP_CLI\Runner->_run_command()
#7 phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#8 phar:///usr/local/bin/wp/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->pro in /var/www/mysite/wp-content/plugins/vcaching/wp-cli.php on line 28
Fatal error: Uncaught Error: Call to undefined method VCaching::purgeUrl() in /var/www/mysitewp-content/plugins/vcaching/wp-cli.php:28
Stack trace:
#0 [internal function]: WP_CLI_VCaching_Purge_Command->purge(Array, Array)
#1 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(81): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(401): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(323): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(330): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(985): WP_CLI\Runner->_run_command()
#7 phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#8 phar:///usr/local/bin/wp/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->pro in /var/www/mysite/wp-content/plugins/vcaching/wp-cli.php on line 28

Any ideas what's going on and how to fix it?

**Comment by ahmed-sigmalux** [comment]
I'm seeing this in the debug.log:

PHP Warning:  Cookie names must not be empty in /var/www/mysite/wp-content/plugins/vcaching/vcaching.php on line 532

**Comment by ahmed-sigmalux** [comment]
I figured it out - there was a typo in the Redis session server in my php.ini. Without a valid Redis server, sessions couldn't be set and vcaching errored out. Fixing that typo and having a valid Redis session server fixed the problem!
